### ISSUE TITLE
/fotografies torna un error

### ISSUE THREAD

**Issue by spdvi** [CIFP-Pau-Casesnoves-DAW/baleart-public-lleoaliciabiel#3]
En fer un GET a [http://www.belmontejuan.com/projecte_baleart/public/api/fotografies](http://www.belmontejuan.com/projecte_baleart/public/api/fotografies)
torna Error: Class &quot;app\Model\Fotografia&quot; not found in file /hosting/www/belmontejuan.com/public/projecte_baleart/app/Http/Controllers/FotografiaController.php on line 14

**Comment by aliciavazquez00** [comment]
Hola, ja ho hem arreglat.
