### ISSUE TITLE
fotografies espai not found

### ISSUE THREAD

**Issue by spdvi** [CIFP-Pau-Casesnoves-DAW/baleart-public-lleoaliciabiel#4]
En fer un GET a http://www.belmontejuan.com/projecte_baleart/public/api/fotografies/espai/1 torna un 404.

**Comment by aliciavazquez00** [comment]
Hola!

Sa URL correcta seria 
http://www.belmontejuan.com/projecte_baleart/public/api/fotografies/espais/1
